# Generated by Django 4.0.1 on 2022-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
    ]
