# Generated by Django 4.0.1 on 2022-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_code_user_datetime_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/media/86a8adc1-febf-43d7-b4cc-e98f4f75f709'),
        ),
    ]
