# Generated by Django 4.0.1 on 2022-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/media/e762beef-06ab-4684-9a33-3ed47ef45298'),
        ),
    ]
