# Generated by Django 4.0.1 on 2022-02-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e29f4c93-938d-453c-96e7-a8ba87ee0c63'),
        ),
    ]
