# Generated by Django 4.0.1 on 2022-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e1663311-10cf-4707-b576-1a0bcfdc367e'),
        ),
    ]
