# Generated by Django 4.0.1 on 2022-02-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/1a73acd6-dedc-45aa-a148-7833c0aa9319'),
        ),
    ]
