# Generated by Django 4.0.1 on 2022-02-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/b4b2ebaa-ed4c-46e2-be2a-2ee797a458bd'),
        ),
    ]
