# Generated by Django 4.0.1 on 2022-02-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/8e4d77e2-f73e-4507-810b-343a18a4d382'),
        ),
    ]
