# Generated by Django 4.0.1 on 2022-02-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/f3e9fd97-feb3-494b-ae10-36cf58e18da2'),
        ),
    ]
