# Generated by Django 4.0.1 on 2022-02-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/9bbd9b5d-81c4-4459-84b4-38ad5bebc3ba'),
        ),
    ]
