# Generated by Django 4.0.2 on 2022-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/7515da1b-054f-480a-a7e1-9dac424a06e4'),
        ),
    ]
