# Generated by Django 4.0.2 on 2022-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/26febf95-b31b-475d-a6fd-d4a4ab3a9d01'),
        ),
    ]
