# Generated by Django 4.0.1 on 2022-02-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/f5869cc1-2b99-461b-a2a6-fe996722eebe'),
        ),
    ]
