# Generated by Django 4.0.1 on 2022-02-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/d2ed55d2-3efb-4a5c-a9c0-25071c0e3537'),
        ),
    ]
