# Generated by Django 4.0.1 on 2022-02-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/476da847-efab-4621-8f3b-6213c4334154'),
        ),
    ]
