# Generated by Django 4.0.1 on 2022-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/c35bee24-c9ab-4ef8-8097-f57a5fb0be58'),
        ),
    ]
