# Generated by Django 4.0.1 on 2022-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endproject',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startproject',
            field=models.DateField(),
        ),
    ]
