# Generated by Django 4.0.1 on 2022-02-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_endproject_alter_project_startproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endproject',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startproject',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
