# Generated by Django 4.0.1 on 2022-02-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_donations',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project_donations',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_donations',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project_donations',
            name='user',
        ),
    ]
