# Generated by Django 4.0.1 on 2022-02-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_comment_delete_project_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
