# Generated by Django 4.0.1 on 2022-02-12 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_donation_delete_project_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Rating_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='projects.project')),
            ],
        ),
    ]
